const ROLES = Object.freeze({ ADMIN: "ADMIN", AGENT: "AGENT", CUSTOMER: "CUSTOMER" });

const POLICY_STATUS = Object.freeze({ ACTIVE: "ACTIVE", EXPIRED: "EXPIRED", CANCELLED: "CANCELLED" });

const CLAIM_STATUS = Object.freeze({ PENDING: "PENDING", APPROVED: "APPROVED", REJECTED: "REJECTED", UNDER_REVIEW: "UNDER_REVIEW" });

const PAYMENT_STATUS = Object.freeze({ PENDING: "PENDING", PAID: "PAID", OVERDUE: "OVERDUE", CANCELLED: "CANCELLED" });

const HTTP_STATUS = Object.freeze({
  OK: 200, CREATED: 201, NO_CONTENT: 204,
  BAD_REQUEST: 400, UNAUTHORIZED: 401, FORBIDDEN: 403,
  NOT_FOUND: 404, CONFLICT: 409, INTERNAL_SERVER_ERROR: 500,
});

const ALLOWED_MIME_TYPES = Object.freeze([
  "application/pdf", "image/jpeg", "image/jpg", "image/png", "image/webp",
]);

const MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024; // 10 MB

module.exports = { ROLES, POLICY_STATUS, CLAIM_STATUS, PAYMENT_STATUS, HTTP_STATUS, ALLOWED_MIME_TYPES, MAX_FILE_SIZE_BYTES };
